version: "4.8"
services:
  mysqldb:
    restart: unless-stopped
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    depends_on:
      - mysqldb
    container_name: springboot-restful-webservices
    image: spring-image
    restart: on-failure
    ports:
      - "9016:9016"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/spring",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",

        "spring.jpa.hibernate.ddl-auto": "create",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.show-sql": true,
        "spring.jpa.generate-ddl": true,

        "spring.thymeleaf.prefix": "classpath:/templates/",
        "spring.thymeleaf.suffix": ".html",
        "spring.thymeleaf.mode": "HTML",
        "spring.thymeleaf.cache": false,
        "spring.thymeleaf.enabled": true,
        "spring.thymeleaf.encoding": "UTF-8",

        "server.port": 8090,

        "spring.mail.host": "smtp.gmail.com",
        "spring.mail.port": 587,
        "spring.mail.username": "hemoharbor@gmail.com",
        "spring.mail.password": "dzme maub jyqh keaa",
        "spring.mail.properties.mail.smtp.starttls.required": true,
        "spring.mail.properties.mail.smtp.starttls.enable": true,

        "spring.web.resources.cache.cachecontrol.cache-private": true,
        "spring.web.resources.cache.cachecontrol.max-age": 31536000,


        "spring.web.resources.add-mappings": true,
        "spring.mvc.static-path-pattern": "/static/**"
        }'
volumes:
   mysql_data: